sudo: required
dist: trusty

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

cache:
  directories:
    - $HOME/.nvm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
  - diego.domingues16@gmail.com, rogerio.alcantara@gmail.com
  slack:
    secure: puI9oyrhrul5lEVx6i0+A6I9puRizGfnY7CN3/3z8e6BV9bpmngeLqtCqf/xNY242Twjrf43qU86BRxDNYzASldmjyRLKQLW4iZth64rO5B3gE+HWLFdLeyEYtl10WmQMJUjd+gJC0oL2FcOhlEmB0mzBv+wOP2ez32Tr1Sv1GgIkYhkDyZVGajTa2XuLeAiCeGQL0cpjXBWk1rQmZUD/z5Tf3HjuPi09RoxpolkMxTH88dXU/mQ/3zMZoOnC/osAACF6jyjh5/XXq/ATZewu1cseLimD5YHqsKG8I8AV26u1kFdbPG8Y54poCC8OXihAe6FhuYwPD7kwNRnecd6CCP79z+orenuHTupeKKpq9k3B/QIarXlYjE0oinQQGPi4BDnNKbmLOWnF6nzkxLOiGhur13E2UaJZppG/ekD4EMvEU/rT5lpPoUqEMectaFQRBguiLFmJRUK6ZF9F8LNBtvjwFXfpRQU/60Sq61UeccqSDwsK8PfJjMbRG8smSlmLIxGiqPu4UMzLCX6npfYfsVl7K/wkLoXZLbIe+eGFR4/4Rb22PIGM6YFR43vPjDwfkeFKluVMzqtvci9TrDp/Y3UriqcP5H5M/blNG24IhbAA4rUJT7VdeOELdzkXtoRenBeOdtWz79j2hf26gOF+ETjLGXHQt5jfbDhXjMtWB8=

branches:
  only:
    - v0.0.1

#
# Build Lifecycle:
#

before_install:
  - npm install -g cordova ionic@beta

install:
  - npm install
  - .travis/setup.sh
  - npm run webdriver-update

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test                             # unit tests
  - npm run build                        # ionic build
  # Serve with python as ionic serve needs interaction
  - cd www && python -m SimpleHTTPServer 8100 >> python_serve.log 2>&1 &
  - npm run e2e                          # run e2e tests against ionic

after_failure:
  - cat /home/travis/build/tango-crew/tango/python_serve.log
  - cat /home/travis/build/tango-crew/tango/ionic_serve.log

after_success:
  # Send coverage info off to cloud ppl
  - cat coverage/lcov.info | ./node_modules/.bin/codecov

before_deploy:
  # start install android
  - wget http://dl.google.com/android/android-sdk_r24.2-linux.tgz
  - tar -xzvf android-sdk_r24.2-linux.tgz
  - echo "y" | ./android-sdk-linux/tools/android list sdk
  - echo "y" | ./android-sdk-linux/tools/android update sdk --no-ui --filter 1,2,3,android-23,41
  - export ANDROID_HOME=${PWD}/android-sdk-linux
  # end install android
  - ionic build android
  # `ionic build android` wraps `cordova build android`, which gives a legit exit code if it fails. Ionic does not; test apk exists.
  - ls ./platforms/android/build/outputs/apk/android*.apk

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: v0.0.1
